# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

V_lambda_tau <- function(K, log_lambda_tau) {
    .Call(`_gwasNocov_V_lambda_tau`, K, log_lambda_tau)
}

beta_tilda <- function(K, x, y, log_lambda_tau) {
    .Call(`_gwasNocov_beta_tilda`, K, x, y, log_lambda_tau)
}

neglr_lambda_tau <- function(log_lambda_tau, K, x, y) {
    .Call(`_gwasNocov_neglr_lambda_tau`, log_lambda_tau, K, x, y)
}

beta_hat_sigma_hat <- function(K, x, y, log_lambda_tau_hat) {
    .Call(`_gwasNocov_beta_hat_sigma_hat`, K, x, y, log_lambda_tau_hat)
}

rcpparma_hello_world <- function() {
    .Call(`_gwasNocov_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_gwasNocov_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_gwasNocov_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_gwasNocov_rcpparma_bothproducts`, x)
}

